# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"8\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\"H\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x12\x10\n\x08voter_id\x18\x03 \x01(\t\":\n\x08LogEntry\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x11\n\toperation\x18\x03 \x01(\t\"n\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x1f\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0c\x63ommit_index\x18\x04 \x01(\x05\"]\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0b\x66ollower_id\x18\x03 \x01(\t\x12\x13\n\x0bmatch_index\x18\x04 \x01(\x05\")\n\x14\x43lientCommandRequest\x12\x11\n\toperation\x18\x01 \x01(\t\"H\n\x12\x43lientCommandReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\"\x0f\n\rStatusRequest\"\x8f\x01\n\x0bStatusReply\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x0c\n\x04term\x18\x03 \x01(\x05\x12\x11\n\tleader_id\x18\x04 \x01(\t\x12\x12\n\nlog_length\x18\x05 \x01(\x05\x12\x14\n\x0c\x63ommit_index\x18\x06 \x01(\x05\x12\x15\n\rstate_machine\x18\x07 \x03(\t2\x8a\x02\n\x04Raft\x12?\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x16.raft.RequestVoteReply\x12\x45\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x18.raft.AppendEntriesReply\x12\x45\n\rClientCommand\x12\x1a.raft.ClientCommandRequest\x1a\x18.raft.ClientCommandReply\x12\x33\n\tGetStatus\x12\x13.raft.StatusRequest\x1a\x11.raft.StatusReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=20
  _globals['_REQUESTVOTEREQUEST']._serialized_end=76
  _globals['_REQUESTVOTEREPLY']._serialized_start=78
  _globals['_REQUESTVOTEREPLY']._serialized_end=150
  _globals['_LOGENTRY']._serialized_start=152
  _globals['_LOGENTRY']._serialized_end=210
  _globals['_APPENDENTRIESREQUEST']._serialized_start=212
  _globals['_APPENDENTRIESREQUEST']._serialized_end=322
  _globals['_APPENDENTRIESREPLY']._serialized_start=324
  _globals['_APPENDENTRIESREPLY']._serialized_end=417
  _globals['_CLIENTCOMMANDREQUEST']._serialized_start=419
  _globals['_CLIENTCOMMANDREQUEST']._serialized_end=460
  _globals['_CLIENTCOMMANDREPLY']._serialized_start=462
  _globals['_CLIENTCOMMANDREPLY']._serialized_end=534
  _globals['_STATUSREQUEST']._serialized_start=536
  _globals['_STATUSREQUEST']._serialized_end=551
  _globals['_STATUSREPLY']._serialized_start=554
  _globals['_STATUSREPLY']._serialized_end=697
  _globals['_RAFT']._serialized_start=700
  _globals['_RAFT']._serialized_end=966
# @@protoc_insertion_point(module_scope)
