# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import twopc_pb2 as twopc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in twopc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwoPCParticipantStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VoteRequest = channel.unary_unary(
                '/twopc.TwoPCParticipant/VoteRequest',
                request_serializer=twopc__pb2.VoteRequestMessage.SerializeToString,
                response_deserializer=twopc__pb2.VoteReply.FromString,
                _registered_method=True)
        self.GlobalDecision = channel.unary_unary(
                '/twopc.TwoPCParticipant/GlobalDecision',
                request_serializer=twopc__pb2.GlobalDecisionMessage.SerializeToString,
                response_deserializer=twopc__pb2.DecisionAck.FromString,
                _registered_method=True)


class TwoPCParticipantServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VoteRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPCParticipantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VoteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteRequest,
                    request_deserializer=twopc__pb2.VoteRequestMessage.FromString,
                    response_serializer=twopc__pb2.VoteReply.SerializeToString,
            ),
            'GlobalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalDecision,
                    request_deserializer=twopc__pb2.GlobalDecisionMessage.FromString,
                    response_serializer=twopc__pb2.DecisionAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.TwoPCParticipant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.TwoPCParticipant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPCParticipant(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VoteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPCParticipant/VoteRequest',
            twopc__pb2.VoteRequestMessage.SerializeToString,
            twopc__pb2.VoteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPCParticipant/GlobalDecision',
            twopc__pb2.GlobalDecisionMessage.SerializeToString,
            twopc__pb2.DecisionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TwoPCCoordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTransaction = channel.unary_unary(
                '/twopc.TwoPCCoordinator/StartTransaction',
                request_serializer=twopc__pb2.TransactionRequest.SerializeToString,
                response_deserializer=twopc__pb2.TransactionResult.FromString,
                _registered_method=True)


class TwoPCCoordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPCCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTransaction,
                    request_deserializer=twopc__pb2.TransactionRequest.FromString,
                    response_serializer=twopc__pb2.TransactionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.TwoPCCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.TwoPCCoordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPCCoordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPCCoordinator/StartTransaction',
            twopc__pb2.TransactionRequest.SerializeToString,
            twopc__pb2.TransactionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TwoPCPhaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeDecision = channel.unary_unary(
                '/twopc.TwoPCPhase/MakeDecision',
                request_serializer=twopc__pb2.InternalDecisionRequest.SerializeToString,
                response_deserializer=twopc__pb2.GlobalDecisionMessage.FromString,
                _registered_method=True)
        self.ApplyDecision = channel.unary_unary(
                '/twopc.TwoPCPhase/ApplyDecision',
                request_serializer=twopc__pb2.InternalApplyDecisionRequest.SerializeToString,
                response_deserializer=twopc__pb2.DecisionAck.FromString,
                _registered_method=True)


class TwoPCPhaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPCPhaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeDecision,
                    request_deserializer=twopc__pb2.InternalDecisionRequest.FromString,
                    response_serializer=twopc__pb2.GlobalDecisionMessage.SerializeToString,
            ),
            'ApplyDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyDecision,
                    request_deserializer=twopc__pb2.InternalApplyDecisionRequest.FromString,
                    response_serializer=twopc__pb2.DecisionAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.TwoPCPhase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.TwoPCPhase', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPCPhase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPCPhase/MakeDecision',
            twopc__pb2.InternalDecisionRequest.SerializeToString,
            twopc__pb2.GlobalDecisionMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPCPhase/ApplyDecision',
            twopc__pb2.InternalApplyDecisionRequest.SerializeToString,
            twopc__pb2.DecisionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
