# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: twopc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'twopc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btwopc.proto\x12\x05twopc\"?\n\x12TransactionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\"W\n\x12VoteRequestMessage\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x16\n\x0e\x63oordinator_id\x18\x03 \x01(\t\"`\n\tVoteReply\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\x13\n\x0bvote_commit\x18\x03 \x01(\x08\x12\x0e\n\x06reason\x18\x04 \x01(\t\"g\n\x15GlobalDecisionMessage\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63oordinator_id\x18\x02 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x03 \x01(\x08\x12\x0e\n\x06reason\x18\x04 \x01(\t\"M\n\x0b\x44\x65\x63isionAck\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"O\n\x11TransactionResult\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x11\n\tcommitted\x18\x02 \x01(\x08\x12\x0f\n\x07summary\x18\x03 \x01(\t\"j\n\x17InternalDecisionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63oordinator_id\x18\x02 \x01(\t\x12\x1f\n\x05votes\x18\x03 \x03(\x0b\x32\x10.twopc.VoteReply\"\x81\x01\n\x1cInternalApplyDecisionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x03 \x01(\x08\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x11\n\toperation\x18\x05 \x01(\t2\x92\x01\n\x10TwoPCParticipant\x12:\n\x0bVoteRequest\x12\x19.twopc.VoteRequestMessage\x1a\x10.twopc.VoteReply\x12\x42\n\x0eGlobalDecision\x12\x1c.twopc.GlobalDecisionMessage\x1a\x12.twopc.DecisionAck2[\n\x10TwoPCCoordinator\x12G\n\x10StartTransaction\x12\x19.twopc.TransactionRequest\x1a\x18.twopc.TransactionResult2\xa4\x01\n\nTwoPCPhase\x12L\n\x0cMakeDecision\x12\x1e.twopc.InternalDecisionRequest\x1a\x1c.twopc.GlobalDecisionMessage\x12H\n\rApplyDecision\x12#.twopc.InternalApplyDecisionRequest\x1a\x12.twopc.DecisionAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twopc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=22
  _globals['_TRANSACTIONREQUEST']._serialized_end=85
  _globals['_VOTEREQUESTMESSAGE']._serialized_start=87
  _globals['_VOTEREQUESTMESSAGE']._serialized_end=174
  _globals['_VOTEREPLY']._serialized_start=176
  _globals['_VOTEREPLY']._serialized_end=272
  _globals['_GLOBALDECISIONMESSAGE']._serialized_start=274
  _globals['_GLOBALDECISIONMESSAGE']._serialized_end=377
  _globals['_DECISIONACK']._serialized_start=379
  _globals['_DECISIONACK']._serialized_end=456
  _globals['_TRANSACTIONRESULT']._serialized_start=458
  _globals['_TRANSACTIONRESULT']._serialized_end=537
  _globals['_INTERNALDECISIONREQUEST']._serialized_start=539
  _globals['_INTERNALDECISIONREQUEST']._serialized_end=645
  _globals['_INTERNALAPPLYDECISIONREQUEST']._serialized_start=648
  _globals['_INTERNALAPPLYDECISIONREQUEST']._serialized_end=777
  _globals['_TWOPCPARTICIPANT']._serialized_start=780
  _globals['_TWOPCPARTICIPANT']._serialized_end=926
  _globals['_TWOPCCOORDINATOR']._serialized_start=928
  _globals['_TWOPCCOORDINATOR']._serialized_end=1019
  _globals['_TWOPCPHASE']._serialized_start=1022
  _globals['_TWOPCPHASE']._serialized_end=1186
# @@protoc_insertion_point(module_scope)
